### ISSUE TITLE
It should be possible to wipe out removed entities via entity inspector

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-datatools#16]
Jmix Studio plugin version: 1.0.SNAPSHOT2581-202
IntelliJ version: IntelliJ IDEA 2020.3.2 (Community Edition)

TC: cretae project>create entity supported soft-delete>run app
create new entity>remove
entity inspetor>show all entities
select removed one

ER: button 'wipe out' should be enabled for removed, softe-deleted entities

**Comment by gorbunkov** [comment]
The new "Wipe out" button should be displayed on the buttons panel. It should be enabled if the entity that supports soft-deletion is currently displayed.
The "Wipe out" button should be enabled both for removed and not removed entities. The button should permanently remove the record from the database.
