### ISSUE TITLE
'Text selection' function doesn`t work for Entity Inspector

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-datatools#19]
Jmix Studio plugin version: 1.0.SNAPSHOT2581-202
IntelliJ version: IntelliJ IDEA 2020.3.2 (Community Edition)

run app>Administration>Entity Inspector
select entity user
set Text selection=true
Show all records
try to select text from record>copy
ER: text shoul be copied
AR: text has not been selected, copid

**Comment by gorbunkov** [comment]
Consider removing this functionality at all
