### ISSUE TITLE
Rows count isn't displayed in entity inspector

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-datatools#28]
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2626-202
IntelliJ version: IntelliJ IDEA 2020.3.2 (Community Edition)

Entity inspector>select Users
ER: row count shuld display
AR: no row count
![image](https://user-images.githubusercontent.com/66992566/110803313-7e44a580-8298-11eb-905b-2ae0ce3024aa.png)

**Comment by gorbunkov** [comment]
Probably, we should use the pagination component for that. See the [issue](https://github.com/Haulmont/jmix-ui/issues/36)
