### ISSUE TITLE
Entity Inspector pretends that it can browse / edit non-persistent model objects

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-datatools#4]
```
@ModelObject(name = "ikna_StudyStat")
public class StudyStat {

    @ModelProperty(mandatory = true)
    @JmixGeneratedValue
    @Id
    private UUID id;

    @ModelProperty
    private LocalDate date;

    @ModelProperty
    private Double successPercent;

...
}
```

![image](https://user-images.githubusercontent.com/6158807/96262663-29478080-0fd3-11eb-8488-f4be547c3ab7.png)

![image](https://user-images.githubusercontent.com/6158807/96262686-32385200-0fd3-11eb-8614-4e117a523ea8.png)

Of course displaying shows zero rows, and editing doesn't work.

**Comment by gorbunkov** [comment]
The issue is not reproduced any more
