### ISSUE TITLE
GraphQL entity restore endpoint

### ISSUE THREAD

**Issue by dtaimanov** [Haulmont/jmix-datatools#44]
#### Task
Need to implement endpoint, which you request to restore removed entities.

#### Implementation
1. Implementation comitted to https://github.com/jmix-projects/jmix-datatools-graphql 
2. `1.1.0-SNAPSHOT` version uploaded to https://nexus.jmix.io
3. Functional test has been added: `io.jmix.datatools.graphql.DatatoolsGraphqlTest#Entity restore endpoint works`
#### Usage:
Add to your build.gradle next dependencies:
```gradle
implementation 'io.jmix.graphql:jmix-graphql-starter'
implementation 'io.jmix.datatools:jmix-datatools-starter'
implementation "io.jmix.datatools:jmix-datatools-graphql-starter:1.1.0-SNAPSHOT"
```

To restore entities by their metaclass name and id list use mutation `restoreEntities(className: String!, ids: [String]!):Int`

**Comment by owlet1997** [comment]
Functional tests for each REST method should be added
